# Generated by Django 4.2.5 on 2023-10-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_myportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='download_resume',
            field=models.URLField(blank=True),
        ),
    ]
