# Generated by Django 4.2.5 on 2023-10-01 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_myprofile_download_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='download_resume',
        ),
        migrations.CreateModel(
            name='ResumeDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_resume', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resume', to='profile_app.myprofile')),
            ],
        ),
    ]
